# Generated by Django 5.0 on 2024-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/uploads'),
        ),
    ]
