# Generated by Django 5.0 on 2024-02-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_car_model_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_model',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
