# Generated by Django 5.0 on 2024-02-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_brand_model_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_one', models.DateTimeField(auto_now_add=True)),
                ('relation_with_car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.car_model', verbose_name='hi')),
            ],
        ),
    ]
