# Generated by Django 5.0 on 2024-02-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_car_brand_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_car_model_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='who_purchased_user_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
